### PR TITLE
Use npm install for all CI jobs

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR fixes the failing CI jobs.

### CODE REVIEW

**Comment by isaacs** [comment]
This should be unnecessary since 38 is landed, yes?

**Comment by DanielRuf** [comment]
Probably but the lockfile is still out of sync (and caused the failing jobs). I thought it would be also good to keep it in sync with the package.json file.

**Comment by DanielRuf** [comment]
Well the general issue is that Travis CI uses `npm ci` starting at specific NodeJS versions so some builds may use different dependencies (depending on if ci or install was used).

Generally it should be set in the Travis CI config to ensure consistent jobs.

**Comment by isaacs** [comment]
CI is passing now, so I think we're good.

**Pull request closed without merging**
