### PR TITLE
fix: restructure .cmd to yield correct errorlevel

### PR DESCRIPTION
**Pull request by staudenmayerc**
This fixes [npm issue #969](https://github.com/npm/cli/issues/969)
(One test still fails, but it also fails without these changes.)

### CODE REVIEW

**Comment by rivy** [comment]
I added a bit of discussion which a couple of suggestions for this on the initial [thread](https://github.com/npm/cli/issues/969#issuecomment-737428940). Also, to prevent regressions, a test showing that `shimmed_cmd_with_error || echo ERROR` outputs "ERROR" would be good.

**Comment by isaacs** [comment]
So if I understand this correctly, the relevant bit here is that the command is the last thing in the batch script, and that avoids the "Terminate batch job (Y/N)?" confirmation?

**Comment by rivy** [comment]
`endLocal & "%_prog%" "<PATH_TO_SCRIPT>" %*` should exit correctly (both ERRORLEVEL and process exit code).

The full `endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%" "<PATH_TO_SCRIPT>" %*` is needed to avoid both the "Terminate batch job (Y/N)?" and correct the ERRORLEVEL/process-exit-code issues. This latter construction can be used anywhere in the script, but as the last line is easily read/understandable and seems like a good choice.

There are more details at <https://github.com/microsoft/terminal/issues/217#issuecomment-737594785> and <https://github.com/npm/cli/issues/969#issuecomment-737428940>.

**Comment by rivy** [comment]
@isaacs , as I've noted above ...

> `@echo off` needs to be within a `@setLocal` (which should be the first executable line), otherwise you are changing it for the calling process as well which can lead to unwanted output or loss of output for scripts calling other scripts.
> To avoid environment pollution for the target executable, use an `endLocal` before calling it. To use your current environment for just the call, use a single parse unit (eg, use `endLocal & "%_prog%" "%dp0%\node_modules\<SCRIPT_PATH>" %*` as the last line).
> - ref: https://github.com/npm/cli/issues/969#issuecomment-737428940

So your commit closing this issue leaves in the noted environmental pollution for both the caller and the called script.

And, it also leaves the "Terminate batch job (Y/N)?" prompt issue unchanged (ie, in the same annoying/broken state).

**Pull request closed without merging**
